name: Lint, Build and Test Server

on:
  pull_request:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Lint, Build and
      - name: Lint, Build and Test Server
        run: |

          cd server
          # Install server dependencies
          npm install
          # Build server, required for seeder
          npm run build

          # Install @bupd/server globally
          npm install -g
          cd seeder
          # Install seeder dependencies
          npm install
          # Linking @bupd/server
          npm link @bupd/server
          # Build seeder
          npm run build

          # Go back to server root
          cd ../
          npm run lint
          npm run test
