name: Lint, Build and Test Server

on:
  pull_request:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Lint, Build and
      - name: Lint, Build and Test Server
        run: |
          npm install
          npm install -g zx
          chmod +x ${GITHUB_WORKSPACE}/scripts/build.js
          zx ${GITHUB_WORKSPACE}/scripts/build.js
