name: Lint, Build and Test Server

on:
  pull_request:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Lint, Build and Test Server
        run: |
          cd server
          # Install server dependencies
          npm install
          # Install bupd-server globally
          npm install -g
          cd seeder
          # Linking bupd-server
          npm link bupd-server
          # Install seeder dependencies
          npm install
          # Build seeder
          npm run build
          # Go back to server root
          cd ../
          npm run lint
          npm run build
          npm run test
