name: Lint, Build, Test and Deploy

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint, Build and Test
        run: |
          cd server
          npm install
          npm run lint
          npm run build
          npm run test
      - name: Deploy Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /
            rm -rf BUPD
            if ! (git clone git@github.com:Devorein/BUPD.git) then
              exit 1
            else
              cd BUPD
              rm -rf client scripts readme.md
              cd server
              npm install
              npm run build
              rm -rf src seeder tests
              pm2 delete api
              pm2 start ./dist/index.js --name api
              echo 'Deployment successful to digital ocean'
            fi
