name: Deploy

on:
  pull_request:
    branches: ["prod"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.actor == 'Devorein' && github.head_ref == 'staging') }}
    steps:
      - name: Deploy Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            bash /deploy.sh
