name: Deploy Server

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Server
        if: ${{ (github.actor == 'Devorein' && github.head_ref == 'staging') }}
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /BUPD
            rm -rf dist
            rm -rf node_modules
            if ! (git clone -b staging --single-branch git@github.com:Devorein/BUPD.git) then
              exit 1
            else
              cd BUPD
              rm -rf client scripts readme.md
              cd server
              npm install
              npm run build
              mv dist ../../
              mv node_modules ../../
              cd ../../
              rm -rf BUPD
              pm2 delete api
              cp .env ./dist
              pm2 start ./dist/index.js --name api
              echo 'Successfully deployed to digital ocean droplet'
            fi
