name: Lint, Build, Test and Deploy

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: |
          cd server
          npm install
      - name: Lint code
        run: |
          cd server
          npm run lint
      - name: Building server
        run: |
          cd server
          npm run build
      - name: Testing server
        run: |
          cd server
          npm run test
